name: New Commit Notification

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [closed]
    branches: [ main, master ]

jobs:
  notify-new-commit:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Get commit information
      id: commit_info
      run: |
        echo "commit_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
        echo "commit_message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
        echo "commit_author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
        echo "commit_date=$(git log -1 --pretty=format:'%ad' --date=short)" >> $GITHUB_OUTPUT
        echo "commit_url=https://github.com/${{ github.repository }}/commit/${{ github.sha }}" >> $GITHUB_OUTPUT
        echo "repo_url=https://github.com/${{ github.repository }}" >> $GITHUB_OUTPUT
    
    - name: Create notification summary
      run: |
        echo "## 🎉 New Commit Alert!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Repository:** ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
        echo "**Commit:** [${{ steps.commit_info.outputs.commit_sha }}](${{ steps.commit_info.outputs.commit_url }})" >> $GITHUB_STEP_SUMMARY
        echo "**Author:** ${{ steps.commit_info.outputs.commit_author }}" >> $GITHUB_STEP_SUMMARY
        echo "**Date:** ${{ steps.commit_info.outputs.commit_date }}" >> $GITHUB_STEP_SUMMARY
        echo "**Message:** ${{ steps.commit_info.outputs.commit_message }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "🔗 [View Repository](${{ steps.commit_info.outputs.repo_url }})" >> $GITHUB_STEP_SUMMARY

    - name: Send notification email (if configured)
      uses: dawidd6/action-send-mail@v3
      if: vars.NOTIFICATION_EMAIL != ''
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "🚀 New Commit in ${{ github.repository }}"
        to: ${{ vars.NOTIFICATION_EMAIL }}
        from: Educational Portal Notifications <${{ secrets.EMAIL_USERNAME }}>
        html_body: |
          <html>
          <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
              <h2 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;">
                🎉 New Commit Alert!
              </h2>
              
              <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <h3 style="margin-top: 0; color: #2c3e50;">Commit Details</h3>
                <p><strong>Repository:</strong> ${{ github.repository }}</p>
                <p><strong>Author:</strong> ${{ steps.commit_info.outputs.commit_author }}</p>
                <p><strong>Date:</strong> ${{ steps.commit_info.outputs.commit_date }}</p>
                <p><strong>Message:</strong> ${{ steps.commit_info.outputs.commit_message }}</p>
              </div>
              
              <div style="text-align: center; margin: 30px 0;">
                <a href="${{ steps.commit_info.outputs.commit_url }}" 
                   style="background-color: #3498db; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
                  View Commit
                </a>
                <a href="${{ steps.commit_info.outputs.repo_url }}" 
                   style="background-color: #2ecc71; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; margin-left: 10px;">
                  View Repository
                </a>
              </div>
              
              <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
              <p style="font-size: 12px; color: #7f8c8d; text-align: center;">
                This notification was automatically generated by the Educational Portal GitHub Actions workflow.
              </p>
            </div>
          </body>
          </html>
      continue-on-error: true

    - name: Post to Slack (if configured)
      uses: 8398a7/action-slack@v3
      if: vars.SLACK_WEBHOOK_URL != ''
      with:
        status: custom
        webhook_url: ${{ vars.SLACK_WEBHOOK_URL }}
        custom_payload: |
          {
            "attachments": [
              {
                "color": "#36a64f",
                "title": "🚀 New Commit in ${{ github.repository }}",
                "title_link": "${{ steps.commit_info.outputs.commit_url }}",
                "fields": [
                  {
                    "title": "Author",
                    "value": "${{ steps.commit_info.outputs.commit_author }}",
                    "short": true
                  },
                  {
                    "title": "Date",
                    "value": "${{ steps.commit_info.outputs.commit_date }}",
                    "short": true
                  },
                  {
                    "title": "Message",
                    "value": "${{ steps.commit_info.outputs.commit_message }}",
                    "short": false
                  }
                ],
                "actions": [
                  {
                    "type": "button",
                    "text": "View Commit",
                    "url": "${{ steps.commit_info.outputs.commit_url }}"
                  },
                  {
                    "type": "button",
                    "text": "View Repository",
                    "url": "${{ steps.commit_info.outputs.repo_url }}"
                  }
                ]
              }
            ]
          }
      continue-on-error: true

    - name: Create commit notification log
      run: |
        mkdir -p notifications
        echo "{
          \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
          \"commit_sha\": \"${{ steps.commit_info.outputs.commit_sha }}\",
          \"commit_message\": \"${{ steps.commit_info.outputs.commit_message }}\",
          \"commit_author\": \"${{ steps.commit_info.outputs.commit_author }}\",
          \"commit_date\": \"${{ steps.commit_info.outputs.commit_date }}\",
          \"commit_url\": \"${{ steps.commit_info.outputs.commit_url }}\",
          \"repository\": \"${{ github.repository }}\",
          \"workflow_run_url\": \"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
        }" > notifications/latest-commit-$(date +%Y%m%d-%H%M%S).json
        
        echo "✅ Notification workflow completed successfully!"
        echo "📧 Email notification: $(if [ '${{ vars.NOTIFICATION_EMAIL }}' != '' ]; then echo 'Sent'; else echo 'Not configured'; fi)"
        echo "💬 Slack notification: $(if [ '${{ vars.SLACK_WEBHOOK_URL }}' != '' ]; then echo 'Sent'; else echo 'Not configured'; fi)"